In [2]:
# First we convert sentences into numbers because neural networks understand only numbers. Then the embedding layer converts each word index into a dense vector that captures the meaning of the word. The sequential model organizes neural network layers in a pipeline where data flows from one layer to the next until the final prediction is produced.
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sentence=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
print(sentence)

['the glass of milk', 'the glass of juice', 'the cup of tea', 'I am a good boy', 'I am a good developer', 'understand the meaning of words', 'your videos are good']


In [5]:
# define the vocabulary size
voc_size=10000

In [6]:
### one hot representation of the sentences
one_hot_repr=[one_hot(words,voc_size) for words in sentence]
print(one_hot_repr)

[[6733, 9544, 7178, 1758], [6733, 9544, 7178, 2363], [6733, 8601, 7178, 9529], [5954, 5221, 3133, 9494, 5652], [5954, 5221, 3133, 9494, 3042], [9640, 6733, 8073, 7178, 766], [6725, 8245, 8758, 9494]]


In [7]:
one_hot_repr[0]

[6733, 9544, 7178, 1758]

In [8]:
### word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [9]:
## define maximum length of the sentence
max_sent_length=8

embedding_docs = pad_sequences(one_hot_repr,maxlen=max_sent_length,padding='pre')

In [10]:
print(embedding_docs)

[[   0    0    0    0 6733 9544 7178 1758]
 [   0    0    0    0 6733 9544 7178 2363]
 [   0    0    0    0 6733 8601 7178 9529]
 [   0    0    0 5954 5221 3133 9494 5652]
 [   0    0    0 5954 5221 3133 9494 3042]
 [   0    0    0 9640 6733 8073 7178  766]
 [   0    0    0    0 6725 8245 8758 9494]]


In [12]:
# feature representation using embedding
dim = 10

In [13]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=max_sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.predict(embedding_docs)

1/1 [==============================] - 0s 300ms/step


array([[[ 0.03404136, -0.02258809,  0.03936793, -0.01718484,
         -0.02054732, -0.04966687, -0.00497733, -0.03679182,
         -0.00334851, -0.00380667],
        [ 0.03404136, -0.02258809,  0.03936793, -0.01718484,
         -0.02054732, -0.04966687, -0.00497733, -0.03679182,
         -0.00334851, -0.00380667],
        [ 0.03404136, -0.02258809,  0.03936793, -0.01718484,
         -0.02054732, -0.04966687, -0.00497733, -0.03679182,
         -0.00334851, -0.00380667],
        [ 0.03404136, -0.02258809,  0.03936793, -0.01718484,
         -0.02054732, -0.04966687, -0.00497733, -0.03679182,
         -0.00334851, -0.00380667],
        [-0.01945126, -0.03556577, -0.00070877, -0.02869271,
          0.03235086,  0.04999861, -0.04748446, -0.04903573,
         -0.04715825, -0.02695931],
        [ 0.04388639,  0.01596088,  0.00622011,  0.02789638,
         -0.04411683, -0.03056486,  0.0078765 ,  0.02490513,
          0.03120558,  0.0310331 ],
        [ 0.02935259, -0.04012246, -0.00589008,  0.0

In [18]:
print(sentence[0])
print(embedding_docs[0])
print(model.predict(embedding_docs[0]))

the glass of milk
[   0    0    0    0 6733 9544 7178 1758]
1/1 [==============================] - 0s 25ms/step
[[ 0.03404136 -0.02258809  0.03936793 -0.01718484 -0.02054732 -0.04966687
  -0.00497733 -0.03679182 -0.00334851 -0.00380667]
 [ 0.03404136 -0.02258809  0.03936793 -0.01718484 -0.02054732 -0.04966687
  -0.00497733 -0.03679182 -0.00334851 -0.00380667]
 [ 0.03404136 -0.02258809  0.03936793 -0.01718484 -0.02054732 -0.04966687
  -0.00497733 -0.03679182 -0.00334851 -0.00380667]
 [ 0.03404136 -0.02258809  0.03936793 -0.01718484 -0.02054732 -0.04966687
  -0.00497733 -0.03679182 -0.00334851 -0.00380667]
 [-0.01945126 -0.03556577 -0.00070877 -0.02869271  0.03235086  0.04999861
  -0.04748446 -0.04903573 -0.04715825 -0.02695931]
 [ 0.04388639  0.01596088  0.00622011  0.02789638 -0.04411683 -0.03056486
   0.0078765   0.02490513  0.03120558  0.0310331 ]
 [ 0.02935259 -0.04012246 -0.00589008  0.04394675  0.02650139  0.02942454
   0.02497183 -0.03521895 -0.01916255  0.00732043]
 [-0.01928802

In [19]:
print(sentence[1])
print(embedding_docs[1])
print(model.predict(embedding_docs[1]))

the glass of juice
[   0    0    0    0 6733 9544 7178 2363]
1/1 [==============================] - 0s 32ms/step
[[ 0.03404136 -0.02258809  0.03936793 -0.01718484 -0.02054732 -0.04966687
  -0.00497733 -0.03679182 -0.00334851 -0.00380667]
 [ 0.03404136 -0.02258809  0.03936793 -0.01718484 -0.02054732 -0.04966687
  -0.00497733 -0.03679182 -0.00334851 -0.00380667]
 [ 0.03404136 -0.02258809  0.03936793 -0.01718484 -0.02054732 -0.04966687
  -0.00497733 -0.03679182 -0.00334851 -0.00380667]
 [ 0.03404136 -0.02258809  0.03936793 -0.01718484 -0.02054732 -0.04966687
  -0.00497733 -0.03679182 -0.00334851 -0.00380667]
 [-0.01945126 -0.03556577 -0.00070877 -0.02869271  0.03235086  0.04999861
  -0.04748446 -0.04903573 -0.04715825 -0.02695931]
 [ 0.04388639  0.01596088  0.00622011  0.02789638 -0.04411683 -0.03056486
   0.0078765   0.02490513  0.03120558  0.0310331 ]
 [ 0.02935259 -0.04012246 -0.00589008  0.04394675  0.02650139  0.02942454
   0.02497183 -0.03521895 -0.01916255  0.00732043]
 [-0.0299749